[build]
  command = "npm run build:style-guide"
  publish = "dist/style-guide"

[build.environment]
  NODE_VERSION = "20"

# Angular workspace SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
