[build]
command = "npm run build -- --project components && npm run build -- --project style-guide"
publish = "dist/style-guide"  # Adjust this path based on your output

[[plugins]]
package = "@netlify/angular-runtime"
