import { Component, OnInit } from '@angular/core';
import { BoostOptions } from 'highcharts';

@Component({
  selector: 'app-icons',
  templateUrl: './icons.component.html',
  styleUrls: ['./icons.component.scss']
})
export class IconsComponent implements OnInit {
  
  materialIcons: Boolean;
  countryFlags: boolean;
  toggleBlade: boolean;

  showSearch: boolean;
  showSearchResults: boolean;
  searchText = '';

  constructor() { }

  flags = [
    'United Arab Emirate - ae',
    'Afghanistan - af',
    'Antigua & Barbuda - ag',
    'Anguilla - ai',
    'Albania - al',
    'Armenia - am',
    'Angola - ao',
    'Argentina - ar',
    'American Samoa	- as',
    'Austria - at',
    'Australia - au',
    'Aruba - aw',
    'Azerbaijan - az',
    'Bosnia & Herzegovina	- ba',
    'Barbados - bb',
    'Bangladesh - bd',
    'Belgium - be',
    'Burkina Faso	- bf',
    'Bulgaria - bg',
    'Bahrain - bh',
    'Burundi - bi',
    'Benin - bj',
    'Bermuda - bm',
    'Brunei Darussalam - bn',
    'Bolivia - bo',
    'Brazil - br',
    'Bahamas (the) - bs',
    'Bhutan - bt',
    'Botswana - bw',
    'Belarus - by',
    'Belize - bz',
    'Canada - ca',
    'Congo (the Dem Rep of the) - cd',
    'Central African Rep (the) - cf',
    'Switzerland - ch',
    'Côte d`Ivoire- ci',
    'Cook Islands (the)	- ck',
    'Chile - cl',
    'Cameroon - cm',
    'China - cn',
    'Colombia - co',
    'Costa Rica	- cr',
    'Cuba - cu',
    'Cabo Verde	- cv',
    'Cyprus - cy',
    'Czechia - cz',
    'Germany - de',
    'Djibouti - dj',
    'Denmark - dk',
    'Dominica - dm',
    'Dominican Rep (the)	- do',
    'Algeria - dz',
    'Ecuador - ec',
    'Estonia - ee',
    'Egypt - eg',
    'Eritrea - er',
    'Spain - es',
    'Ethiopia - et',
    'Finland - fi',
    'Fiji - fj',
    'Falkland Islands (the) [Malvinas] - fk',
    'Micronesia (Federated States of) - fm',
    'Faroe Islands (the) - fo',
    'France - fr',
    'Gabon - ga',
    'United Kingdom of GB & NI (the) - gb',
    'Grenada - gd',
    'Georgia - ge',
    'Ghana - gh',
    'Gibraltar - gi',
    'Greenland - gl',
    'Gambia (the)	- gm',
    'Guinea - gn',
    'Guadeloupe - gp',
    'Equatorial Guinea - gq',
    'Greece - gr',
    'Guam - gu',
    'Guinea-Bissau - gw',
    'Guyana - gy',
    'Hong Kong - hk',
    'Honduras - hn',
    'Croatia - hr',
    'Haiti - ht',
    'Hungary - hu',
    'Indonesia - id',
    'Ireland - ie',
    'Israel - il',
    'Isle of Man - im',
    'India - in',
    'Iraq - iq',
    'Iran (Islamic Rep of) - ir',
    'Italy - it',
    'Jamaica - jm',
    'Jordan - jo',
    'Japan - jp',
    'Kenya - ke',
    'Kyrgyzstan - kg',
    'Cambodia - kh',
    'Kiribati - ki',
    'Comoros (the) - km',
    'Saint Kitts & Nevis - kn',
    'Korea (the Democratic People`s Rep of) - kp',
    'Korea (the Rep of) - kr',
    'Kuwait - kw',
    'Cayman Islands (the) - ky',
    'Kazakhstan - kz',
    'Lao People`s Democratic Rep (the) - la',
    'Lebanon - lb',
    'Saint Lucia - lc',
    'Liechtenstein - li',
    'Sri Lanka - lk',
    'Liberia - lr',
    'Lesotho - ls',
    'Lithuania - lt',
    'Luxembourg - lu',
    'Latvia - lv',
    'Libya - ly',
    'Morocco - ma',
    'Monaco - mc',
    'Moldova (the Rep of) - md',
    'Montenegro - me',
    'Madagascar - mg',
    'Marshall Islands (the) - mh',
    'Rep of North Macedonia - mk',
    'Mali - ml',
    'Myanmar - mm',
    'Mongolia - mn',
    'Macao - mo',
    'Mauritania - mr',
    'Montserrat - ms',
    'Malta - mt',
    'Mauritius - mu',
    'Maldives - mv',
    'Malawi - mw',
    'Mexico - mx',
    'Malaysia - my',
    'Mozambique - mz',
    'Namibia - na',
    'New Caledonia - nc',
    'Niger (the) - ne',
    'Nigeria - ng',
    'Nicaragua - ni',
    'Netherlands (the) - nl',
    'Norway - no',
    'Nepal - np',
    'Nauru - nr',
    'New Zealand - nz',
    'Oman - om',
    'Panama - pa',
    'Peru - pe',
    'Philippines (the) - ph',
    'Pakistan - pk',
    'Poland - pl',
    'Puerto Rico - pr',
    'Palestine, State of - ps',
    'Palau - pw',
    'Paraguay - py',
    'Qatar - qa',
    'Romania - ro',
    'Serbia - rs',
    'Russian Federation (the) - ru',
    'Rwanda - rw',
    'Saudi Arabia - sa',
    'Solomon Islands - sb',
    'Seychelles - sc',
    'Sudan (the) - sd',
    'Sweden - se',
    'Singapore - sg',
    'Slovenia - si',
    'Slovakia - sk',
    'Slovenia - sl',
    'San Marino - sm',
    'Senegal - sn',
    'Somalia - so',
    'Suriname - sr',
    'South Sudan - ss',
    'Sao Tome & Principe - st',
    'El Salvador - sv',
    'Syrian Arab Rep - sy',
    'Eswatini - sz',
    'Turks & Caicos Islands (the) - tc',
    'Chad - td',
    'Togo - tg',
    'Thailand - th',
    'Tajikistan - tj',
    'Timor-Leste - tl',
    'Turkmenistan - tm',
    'Tunisia - tn',
    'Tonga - to',
    'Turkey - tr',
    'Trinidad & Tobago - tt',
    'Tuvalu - tv',
    'Taiwan (Province of China) - tw',
    'Tanzania, United Rep of - tz',
    'Ukraine - ua',
    'Uganda - ug',
    'United States of America (the) - us',
    'Uruguay - uy',
    'Uzbekistan - uz',
    'Saint Vincent & the Grenadines - vc',
    'Venezuela (Bolivarian Rep of) - ve',
    'Virgin Islands (British) - vg',
    'irgin Islands (U.S.) - vi',
    'Vietnam - vn',
    'Samoa - ws',
    'Vanuatu - vu',
    'Yemen - ye',
    'South Africa - za',
    'Zimbabwe - zw',
    'Zambia - zm'
  ];

  toggleSearchInput() {
    this.showSearch = ! this.showSearch;
    if(this.showSearch) {
      document.getElementById('search-text').focus();
    } else {
      this.searchText = '';
    }
  }
  
  bladeIsOpen(open: boolean) {
    this.toggleBlade = open;
  }

  ngOnInit() {
  }

}
