trigger:
  branches:
    include:
      - master
  paths:
    include:
      - workspace/projects/styles/*
    exclude:
      - workspace/projects/styles/src/scss/widgets/_design-lang-ui.scss

pool:
  vmImage: 'ubuntu-latest'

variables:
  Version.MajorMinor: 17.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

steps:
  - task: Npm@1
    displayName: Version
    inputs:
      command: custom
      workingDir: workspace/projects/styles
      customCommand: version $(Version.MajorMinor).$(Version.Revision) --git-tag-version=false --commit-hooks=false
  - task: Npm@1
    displayName: Publish to Core feed
    inputs:
      command: publish
      workingDir: workspace/projects/styles
      publishRegistry: useFeed
      publishFeed: Core
